config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/new", to: "games#new"
  get "/score", to: "games#score"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    alphabet = ('a'..'z').to_a
    @random_letters = Array.new(10) { alphabet.sample }
  end
  def score
    result = params[:answer]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="container text-left mt-5">
  <h1>
    <p class="text-left">New Game</p>
    <% @random_letters.each do |letter| %>
      <span class="badge badge-primary mr-2"><%= letter.upcase %></span>
    <% end %>
  </h1>
</div>
<div class="container mt-5">
  <div class="row justify-content-left">
    <div class="col-md-6">
      <div class="ml-3">
        <%= form_tag score_path, method: :get do %>
          <div class="form-group">
            <%= label_tag :question, "What is the longest word that you can find?" %>
            <%= text_field_tag :answer, nil, class: "form-control" %>
          </div>
          <%= submit_tag "Play", class: "btn btn-danger mt-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/games/score.html.erb
<h1>Result</h1>

<%= link_to "Play again!", new_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>